version: "3"

services:
  api:
    image: node:14.13.1
    working_dir: /app
    volumes:
      - ./:/app
    command: "npm run dev"
    ports:
      - "8080:8080"
      
  database:
    image: mongo:4.2
    environment:
        - MONGO_INITDB_DATABASE=database
        - MONGO_INITDB_USERNAME=user
        - MONGO_INITDB_PASSWORD=changeme
    volumes:
        - ./mongo-volume:/data/db
    ports:
        - '27017:27017'

  dbmanager:
    image: mongo-express:0.54
    ports:
      - "8081:8081"
    links:
      - database:mongo